apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: revelaservices-cert
  namespace: default
spec:
  secretName: revelaservices-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - test.revelaservices.in
